### ISSUE TITLE
2020년 신년 목표 달성

### ISSUE THREAD

**Issue by crontable** [sannimdev/sannimdev#1]
- 매일 1일 1커밋

![image](https://user-images.githubusercontent.com/22428471/103480300-e39e9500-4e16-11eb-8fd2-81eb270dec76.png)

**Comment by crontable** [comment]
이미지 교체

![image](https://user-images.githubusercontent.com/22428471/105988622-45cf7a80-60e3-11eb-93a3-4d7b4a8f9c5c.png)

**Comment by sannimdev** [comment]
![Uploading image.png…]()

**Comment by crontable** [comment]
![image](https://user-images.githubusercontent.com/22428471/107121136-2ea73e80-68d4-11eb-978d-a787be00b168.png)
![image](https://user-images.githubusercontent.com/22428471/107853075-54de5880-6e57-11eb-9477-5c90aa661ea4.png)
